[project]
name = "wa_rpa"
version = "26.8.2"
description = "Automações WhatsApp - Versão atualizada do AuthWA"
readme = "README.md"

authors = [
    { name = "Guilherme Breve", email = "64221923+foxtec198@users.noreply.github.com" }
]

requires-python = ">=3.9,<4.0"

classifiers = [
    "Programming Language :: Python :: 3.11",
    "Environment :: Console",
    "Development Status :: 5 - Production/Stable",
    "Natural Language :: Portuguese (Brazilian)",
    "Intended Audience :: Developers",
]

[project.urls]
"Documentação" = "https://authwa.readthedocs.io"


[tool.poetry]
packages = [
    { include = "wa_rpa.py" }
]


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"


[tool.poetry.group.docs.dependencies]
mkdocs-material = "^9.5.9"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"